[git] Don't commit/push to develop branch.

diff --git a/.git_hooks/pre-commit b/.git_hooks/pre-commit
--- a/.git_hooks/pre-commit
+++ b/.git_hooks/pre-commit
@@ -5,3 +5,9 @@ if [ "${branch##refs/heads/}" = "master" ]; then
   echo "Please commit on topic branch."
   exit 1
 fi
+
+if [ "${branch##refs/heads/}" = "develop" ]; then
+  echo "Can't commit on develop branch."
+  echo "Please commit on topic branch."
+  exit 1
+fi
diff --git a/.git_hooks/pre-push b/.git_hooks/pre-push
--- a/.git_hooks/pre-push
+++ b/.git_hooks/pre-push
@@ -6,4 +6,8 @@ do
     echo "Can't push to master branch."
     exit 1
   fi
+  if [ "${remote_ref##refs/heads/}" = "develop" ]; then
+    echo "Can't push to develop branch."
+    exit 1
+  fi
 done
