[git] main ブランチも保護対象にする

diff --git a/.git_hooks/pre-commit b/.git_hooks/pre-commit
--- a/.git_hooks/pre-commit
+++ b/.git_hooks/pre-commit
@@ -6,6 +6,12 @@ if [ "${branch##refs/heads/}" = "master" ]; then
   exit 1
 fi
 
+if [ "${branch##refs/heads/}" = "main" ]; then
+  echo "Can't commit on master branch."
+  echo "Please commit on topic branch."
+  exit 1
+fi
+
 if [ "${branch##refs/heads/}" = "develop" ]; then
   echo "Can't commit on develop branch."
   echo "Please commit on topic branch."
diff --git a/.git_hooks/pre-push b/.git_hooks/pre-push
--- a/.git_hooks/pre-push
+++ b/.git_hooks/pre-push
@@ -6,6 +6,10 @@ do
     echo "Can't push to master branch."
     exit 1
   fi
+  if [ "${remote_ref##refs/heads/}" = "main" ]; then
+    echo "Can't push to master branch."
+    exit 1
+  fi
   if [ "${remote_ref##refs/heads/}" = "develop" ]; then
     echo "Can't push to develop branch."
     exit 1
